FROM apache/airflow:2.9.1

RUN pip install --no-cache-dir \
    yfinance==1.3.0 \
    pandas \
    numpy \
    psycopg2-binary \
    sqlalchemy \
    scikit-learn \
    xgboost \
    tensorflow \
    keras